name: Fashion News Daily

on:
  schedule:
    - cron: '0 0 * * *'  # 매일 오전 9시 (UTC 00:00 = KST 09:00)
  workflow_dispatch:  # 수동 실행 가능

jobs:
  send-news:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        pip install requests beautifulsoup4 schedule
        
    - name: Run fashion news bot
      env:
        NAVER_CLIENT_ID: ${{ secrets.NAVER_CLIENT_ID }}
        NAVER_CLIENT_SECRET: ${{ secrets.NAVER_CLIENT_SECRET }}
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      run: |
        python fashion_news_bot.py
